name: Publish Release
on:
  pull_request:
    types: [closed]
    branches:
      - 'main'
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: abatilo/release-info-action@v1.3.0    
        name: Get Latest Release
        id: latest_version
        with:
          owner: EPM devs
          repo: testingGHA
        env:
          LATEST: ${{ steps.latest_version.outputs.latest_tag }}
          LATEST_DATE: ${{ steps.latest_version.outputs.latest_tag_published_at }}