name: Update QA/Testing from main

on:
  pull_request:
    types: [closed]
    branches:
      - 'main'
    tags: 
      - 'v*' 

jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Merge main -> otherBranch
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: main
          target_branch: otherBranch
          github_token: ${{ github.token }}   
      - name: Get Latest Release
        id: latest_version
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}