name: Update QA/Testing from main

on:
  pull_request:
    types: [closed]
    branches:
      - 'main'
    tags: 
      - 'v*' 

jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Merge main -> otherBranch
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: main
          target_branch: otherBranch
          github_token: ${{ github.token }}      
      
      - name: Get Latest Release
        id: latest_version
      - uses: abatilo/release-info-action@v1.3.0
        with:
          owner: EPM devs
          repo: EPM_CORE_API
        env:
          tag_name: ${{ steps.latest_version.outputs.latest_tag }}
          LATEST_DATE: ${{ steps.latest_version.outputs.latest_tag_published_at }}
        run: |
          echo "Version $LATEST was released at $LATEST_DATE"
    
